version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/content_collector
    depends_on:
      - db
    command: ["python", "-m", "content_collector.cli.main"]

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=content_collector

volumes:
  postgres_data: