name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest tests/unit
          pytest tests/integration
          pytest tests/e2e

      - name: Lint code
        run: |
          flake8 src/
          black --check src/
          isort --check-only src/

      - name: Build Docker image
        run: |
          docker build -t content-collector .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag content-collector:latest your-docker-repo/content-collector:latest
          docker push your-docker-repo/content-collector:latest